### ISSUE TITLE
blueprint-dab should just be dab

### ISSUE THREAD

**Issue by technetos** [onehilltech/blueprint-gatekeeper#2]
[https://github.com/onehilltech/blueprint-gatekeeper/blob/master/examples/dab.js#L1](https://github.com/onehilltech/blueprint-gatekeeper/blob/master/examples/dab.js#L1)

```Node
const dab = require ('@onehilltech/blueprint-dab')
```

Should be

```Node
const dab = require ('@onehilltech/dab')
```

**Comment by hilljh82** [comment]
This issue has been fixed.
