### ISSUE TITLE
Gatekeeper cors for hybrid applications

### ISSUE THREAD

**Issue by AndyV99** [onehilltech/blueprint-gatekeeper#6]
Gatekeeper cors should not be active when you are targeting a hybrid mobile application.

**Comment by hilljh82** [comment]
@AndyV99 We have fixed this issue and released a patch. You can now pass in default options to the `cors()` method. 

When testing a hybrid mobile application, a CORS request will still be sent over the network. Unfortunately, if you did not register your client as a recaptcha client, then the CORS request failed. To get around this problem, just pass in `{origin: true}` to the `cors()` function:

```javascript
const { env } = require ('@onehilltech/blueprint');
const { cors } = require ('@onehilltech/blueprint-gatekeeper');

module.exports = {
  '/v1': {
    use: [cors ({
      origin: env !== 'production' ? true : null
    })]
  }
};
```

In this example above, we are always enabling CORS when we are not in production. This should allow native clients to work during both development, testing, and production (there is no origin in a request from a mobile client).
